name: Feature Branch to Development

on:
  pull_request:
    branches:
      - development

jobs:
  code-analysis:
    runs-on: macos-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install Swift
        run: |
          brew update
          brew install swift
          swift --version

      - name: Install dependencies
        run: |
          if [ -f "Podfile" ]; then
            gem install cocoapods
            pod install
          fi
          if [ -f "Cartfile" ]; then
            brew install carthage
            carthage bootstrap --platform iOS
          fi

      - name: Install Periphery
        run: |
          brew install periphery
          periphery --version

      - name: Set up Xcode Command Line Tools
        run: |
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -runFirstLaunch

      - name: Boot iOS Simulator
        run: |
          xcrun simctl boot "iPhone 14"
          xcrun simctl list devices

      - name: Build for iOS Simulator (Explicit Destination)
        run: |
          xcodebuild -project test_github_action.xcodeproj -scheme "test_github_action" -destination "platform=iOS Simulator,name=iPhone 14" -derivedDataPath /tmp/derived_data build

      - name: Run Periphery with simulator
        run: |
          periphery scan --project test_github_action.xcodeproj --schemes "test_github_action" --platform iOS --device "iPhone 14" --verbose

  merge:
    needs: code-analysis
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git configuration
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Merge feature branch into development
        run: |
          git fetch origin development
          git checkout development
          git merge --no-ff ${{ github.head_ref }}

      - name: Push merged changes to development
        run: git push origin development
